name: mpflutter
description: The MPFlutter Library
publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: any
  full_screen_back_gesture: 0.0.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
