name: mpflutter
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  mpflutter:

dependencies:
  args: ^2.0.0
  path: ^1.8.0
  io: ^1.0.0
  crypto: ^3.0.1
  yaml: ^3.1.0
  cli_menu: ^0.3.0-nullsafety.0