name: mpcore
description: The MPFlutter core libs.
publish_to: none
version: 0.0.1
homepage: /

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter: any
  vm_service: ^6.2.0
  watcher: ^1.1.0
  glob: "^2.1.1"
  mime_type: ^1.0.0
  path: ^1.8.0
  usage: ^4.0.2

dependency_overrides:
  flutter: 
    path: ../flutter